# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClothIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClothInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_NAME', models.CharField(default='', max_length=50)),
                ('CLOTH_FACTORY', models.CharField(default='', max_length=100)),
                ('CLOTH_STATUS', models.IntegerField(default='1')),
                ('CLOTH_IMG', models.CharField(default='', max_length=100)),
                ('CLOTH_TOP', models.IntegerField(default='')),
                ('CREATE_TIME', models.CharField(default='2018-05-01', max_length=100)),
                ('CONTENT', models.TextField(default='', max_length=255)),
                ('CLOTH_REMAIN', models.FloatField(default=0.0)),
                ('CLOTH_DEAL_REMAIN', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClothOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.FloatField(default=0.0)),
                ('CUSTOMER', models.CharField(default='', max_length=50)),
                ('AMOUNT', models.FloatField(default=0.0)),
                ('CREATE_TIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothPieceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_PIECE', models.FloatField(default=0.0)),
                ('CLOTH_PIECE_COUNT', models.FloatField(default=0.0)),
            ],
        ),
    ]
