# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteClothInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_NAME', models.CharField(default='', max_length=50)),
                ('CLOTH_REMAIN', models.FloatField(default=0.0)),
                ('CLOTH_DEAL_REMAIN', models.FloatField(default=0.0)),
            ],
        ),
    ]
