# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClothIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClothOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOTH_CODE', models.CharField(default='', max_length=10)),
                ('CLOTH_COUNT', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='clothinfo',
            name='CLOTH_DEAL_REMAIN',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothinfo',
            name='CLOTH_REMAIN',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
