# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0002_auto_20180504_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothdeal',
            name='CLOTH_COUNT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothin',
            name='CLOTH_COUNT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothinfo',
            name='CLOTH_DEAL_REMAIN',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothinfo',
            name='CLOTH_REMAIN',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothout',
            name='CLOTH_COUNT',
            field=models.FloatField(default=0.0),
        ),
    ]
