# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0003_clothpieceinfo_remaeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothpieceinfo',
            old_name='Remaeks',
            new_name='REMARKS',
        ),
    ]
