# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0005_clothout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothout',
            name='CREATE_TIME',
            field=models.CharField(default='2018-05-01', max_length=100),
        ),
    ]
