# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0005_auto_20180524_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothout',
            name='CREATE_TIME',
            field=models.DateField(auto_now=True),
        ),
    ]
