# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0006_clothout_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothout',
            name='CREATE_TIME',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
