# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0007_auto_20180608_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER', models.CharField(default='', max_length=50)),
                ('CLOTH_PIECE', models.FloatField(default=0.0)),
                ('CLOTH_COUNT', models.FloatField(default=0.0)),
                ('AMOUNT', models.FloatField(default=0.0)),
                ('ORDER_TIME', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='clothpieceinfo',
            name='ORDER_ID',
            field=models.IntegerField(default=0),
        ),
    ]
