# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0008_auto_20180611_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='CLOTH_PIECE',
            field=models.IntegerField(default=0),
        ),
    ]
