# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0009_auto_20180611_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothpieceinfo',
            name='EDIT_CLOTH_COUNT',
            field=models.FloatField(default=0.0),
        ),
    ]
