# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_manage', '0010_clothpieceinfo_edit_cloth_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothpieceinfo',
            name='AMOUNT',
            field=models.FloatField(default=0.0),
        ),
    ]
