# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('SUPPLIER_NAME', models.CharField(max_length=50)),
            ],
        ),
    ]
